export const addDay = () => ({ type: 'add_day', payload: null });
export const deleteDay = (day) => ({ type: 'delete_day', payload: day });
export const addActivity = () => ({ type: 'add_activity', payload: null });
export const deleteActivity = (activity) => ({ type: 'delete_activity', payload: activity });
export const updateDate = (date) => ({ type: 'update_date', payload: date });
export const updateActivity = (activity) => ({ type: 'update_activity', payload: activity });
export const updateActiveDay = (day) => ({ type: 'update_active_day', payload: day });
export const updateActiveActivity = (activity) => ({ type: 'update_active_activity', payload: activity });
export const initializeStore = (username, days, activities) => ({ type: 'initialize_store', payload: { username, days, activities } });
export const calculateStatistics = () => ({ type: 'calculate_statistics', payload: null });
